export const ESTADO_LABELS = {
  PENDIENTE_INICIO_GESTION: "Inicio",
  PENDIENTE_DIRECCION_MEDICA: "Dir. Médica",
  PENDIENTE_ASESORIA_JURIDICA: "Jurídica",
  PENDIENTE_DOCUMENTACION_DEL_ASEGURADO: "Documentación",
  PENDIENTE_REVISION_PRESTACIONES: "Revisión",
  AUTORIZADA: "Autorizada",
  RECHAZADA: "Rechazada",
};
