export const ESTADOS = {
  PENDIENTE_INICIO_GESTION: "PENDIENTE_INICIO_GESTION",
  DOCUMENTACION_SOLICITADA: "DOCUMENTACION_SOLICITADA",
  EN_REVISION: "EN_REVISION",
  DIRECCION_MEDICA: "DIRECCION_MEDICA",
  ASESORIA_JURIDICA: "ASESORIA_JURIDICA",
  AUTORIZADA: "AUTORIZADA",
  RECHAZADA: "RECHAZADA",
  PENDIENTE_REVISION_PRESTACIONES: "PENDIENTE_REVISION_PRESTACIONES",
  PENDIENTE_DIRECCION_MEDICA: "PENDIENTE_DIRECCION_MEDICA",
  PENDIENTE_DOCUMENTACION_DEL_ASEGURADO:
    "PENDIENTE_DOCUMENTACION_DEL_ASEGURADO",
};
