const ESTADOS_SOLICITUD = {
  PENDIENTE_INICIO_GESTION: "PENDIENTE_INICIO_GESTION",
  DOCUMENTACION_SOLICITADA: "DOCUMENTACION_SOLICITADA",
  EN_REVISION: "EN_REVISION",
  AUTORIZADA: "AUTORIZADA",
  RECHAZADA: "RECHAZADA",
};

module.exports = ESTADOS_SOLICITUD;
