const solicitudFlowRules = {
  PENDIENTE_INICIO_GESTION: [
    "PENDIENTE_DIRECCION_MEDICA",
    "AUTORIZADA",
    "RECHAZADA",
  ],

  PENDIENTE_DIRECCION_MEDICA: [
    "PENDIENTE_DOCUMENTACION_DEL_ASEGURADO",
    "AUTORIZADA",
    "RECHAZADA",
  ],

  PENDIENTE_ASESORIA_JURIDICA: [
    "PENDIENTE_DOCUMENTACION_DEL_ASEGURADO",
    "AUTORIZADA",
    "RECHAZADA",
  ],

  PENDIENTE_DOCUMENTACION_DEL_ASEGURADO: ["PENDIENTE_REVISION_PRESTACIONES"],

  PENDIENTE_REVISION_PRESTACIONES: [
    "PENDIENTE_DIRECCION_MEDICA",
    "PENDIENTE_ASESORIA_JURIDICA",
  ],

  AUTORIZADA: [],

  RECHAZADA: [],
};

module.exports = solicitudFlowRules;
